name: Publish kraken
on: push
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install jq
        run: |-
          curl -sSLo /usr/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
          chmod +x /usr/bin/jq
      - name: Check if version is already published to npm
        id: version_check
        run: |-
          PACKAGE="@pennlabs/kraken"
          VERSION=0.8.4
          NEW_VERSION=$(yarn info $PACKAGE versions --json | jq ".data | any(. == \"$VERSION\") | not")
          echo "::set-output name=NEW_VERSION::$NEW_VERSION"
      - name: Publish to npm
        run: |-
          echo "publishing new version"
        if: github.ref == 'refs/heads/main' && steps.version_check.outputs.NEW_VERSION
    container:
      image: node:14
